-- Database: `warhex_db`
CREATE DATABASE IF NOT EXISTS `warhex_db`;
USE `warhex_db`;

-- Table structure for table `admin_users`
CREATE TABLE IF NOT EXISTS `admin_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert default admin (password is 'admin123' generated by password_hash)
INSERT INTO `admin_users` (`id`, `username`, `password`) VALUES
(1, 'admin', '$2y$10$8.4.T8UqE1s.L5X3xIe7Q.aXz23p89D0J6zV1rRzK9H3z6w5W.6w6'); 
-- password is 'admin123'

-- Table structure for table `products`
CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `image` varchar(255) NOT NULL,
  `cell_class` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table `products`
INSERT INTO `products` (`id`, `title`, `description`, `image`, `cell_class`) VALUES
(1, 'HEX Controller Pro', 'Tactile precision switches, zero-latency wireless, and a grip molded for long-battle endurance.', 'assets/WarHex1.png', 'prod-cell--b'),
(2, 'WarHex Mech Figurine', 'Limited edition 1:12 scale Iron Horizon Unit-01. Hand-painted, numbered, battle-worn finish.', 'assets/WarHex3.png', 'prod-cell--d prod-cell--reverse'),
(3, 'Iron Horizon Headset', 'Spatial audio with 7.1 surround. Hear the battlefield before you see it.', 'assets/WarHex5.jpg', 'prod-cell--e'),
(4, 'HEX Combat Jacket', 'Tactical-grade fabric, embroidered WarHex insignia, built for the streets and the arena.', 'assets/WarHex4.png', 'prod-cell--f');
